package main

// codex shim：PATH 上一个名为 codex 的包装，验证 router 活着后
// exec 真 codex。移植 codex-shim.mjs 的安全约束：
//   1. 只经 `shim install` 显式安装，任何自动路径（install/doctor）
//      都不得装它；
//   2. 只写用户 home 内的 PATH 目录 —— /usr/local/bin 会改全机器的 codex；
//   3. 绝不覆盖/删除不带 SHIM_MARKER 的 codex（别人的 wrapper 是刻意
//      设置，不是碎片）；
//   4. 不改 shell 启动文件；无 home 内目录可写时打印 export 行并停止；
//   5. 生成的 shim 每条失败路径都 exec 真 codex —— 坏 router 绝不能
//      变成"codex 启动不了"。

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// shimMarker 是 shim 文件的标识（不带它的 codex 绝不碰）。
const shimMarker = "MODEL_ROUTER_CODEX_SHIM"
const shimCommand = "codex"
const fallbackShimDir = "~/.local/bin"

// renderShim 生成 bash shim（用 /dev/tcp 探活，零 fork）。
func renderShim(realCodex, checkout string, port int) string {
	var out strings.Builder
	out.WriteString("#!/bin/bash\n")
	out.WriteString("# " + shimMarker + "\n")
	out.WriteString("#\n")
	out.WriteString("# Generated by `codex-router shim install`. Ensures the Codex Router is\n")
	out.WriteString("# listening, then hands off to the real Codex. Remove it with\n")
	out.WriteString("# `codex-router shim uninstall`, or just delete this file.\n")
	out.WriteString("#\n")
	out.WriteString("# Every failure path here still execs Codex. A router problem must never be\n")
	out.WriteString("# allowed to become \"codex does not start\".\n")
	out.WriteString("\nset -u\n\n")
	fmt.Fprintf(&out, "ROUTER_CHECKOUT=%q\n", checkout)
	fmt.Fprintf(&out, "ROUTER_PORT=%q\n", fmt.Sprintf("%d", port))
	fmt.Fprintf(&out, "CODEX_BIN=%q\n", realCodex)
	out.WriteString("ROUTER_WAIT=${MODEL_ROUTER_SHIM_WAIT:-45}\n\n")
	out.WriteString(`# Recorded at install time, but npm reinstalls and version managers move
# things. Fall back to a PATH search that skips this shim rather than failing.
if [ ! -x "$CODEX_BIN" ]; then
  found=''
  saved_ifs=$IFS
  IFS=:
  for dir in $PATH; do
    [ -n "$dir" ] || dir='.'
    candidate="$dir/codex"
    if [ -x "$candidate" ] && ! grep -q '` + shimMarker + `' "$candidate" 2>/dev/null; then
      found=$candidate
      break
    fi
  done
  IFS=$saved_ifs
  if [ -z "$found" ]; then
    printf 'codex-router: cannot find the real codex on PATH.\n' >&2
    exit 127
  fi
  CODEX_BIN=$found
fi

router_listening() {
  (exec 3<>"/dev/tcp/127.0.0.1/$ROUTER_PORT") 2>/dev/null
}

# MODEL_ROUTER_SHIM=0 is the escape hatch for debugging Codex without the
# router in the way.
if [ "${MODEL_ROUTER_SHIM:-1}" != '0' ] && ! router_listening; then
  if [ -x "$ROUTER_CHECKOUT/codex-router" ] || [ -x "$ROUTER_CHECKOUT/bin/codex-router" ]; then
    printf 'codex-router: starting the router...\n' >&2
    ("$ROUTER_CHECKOUT/codex-router" control service start >/dev/null 2>&1) &
    waited=0
    while [ "$waited" -lt "$ROUTER_WAIT" ]; do
      if router_listening; then break; fi
      sleep 1
      waited=$((waited + 1))
    done
    if ! router_listening; then
      printf 'codex-router: the router did not come up in %ss; starting Codex anyway.\n' "$ROUTER_WAIT" >&2
    fi
  else
    printf 'codex-router: checkout missing at %s; starting Codex without the router.\n' "$ROUTER_CHECKOUT" >&2
  fi
fi

exec "$CODEX_BIN" "$@"
`)
	return out.String()
}

// isShimFile 报告文件是否本程序生成的 shim。
func isShimFile(path string) bool {
	raw, err := os.ReadFile(path)
	return err == nil && strings.Contains(string(raw), shimMarker)
}

// resolveRealCodex 找 PATH 上第一个非 shim 的 codex。
func resolveRealCodex() string {
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" {
			continue
		}
		candidate := filepath.Join(dir, shimCommand)
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			if !isShimFile(candidate) {
				return candidate
			}
		}
	}
	return ""
}

// shimTargetDir 选安装目录：PATH 上第一个位于 home 内且排在真 codex
// 之前的可写目录；找不到时退回 ~/.local/bin（可能不在 PATH ——
// 打印 export 行让操作者决定）。
func shimTargetDir(home, realCodex string) (string, bool) {
	entries := filepath.SplitList(os.Getenv("PATH"))
	realDir := ""
	if realCodex != "" {
		realDir = filepath.Dir(realCodex)
	}
	inHome := func(dir string) bool {
		return strings.HasPrefix(dir, home)
	}
	// 先找排在真 codex 之前的 home 内目录（保证优先级正确）。
	beforeReal := true
	for _, dir := range entries {
		if dir == "" {
			continue
		}
		if dir == realDir {
			beforeReal = false
			continue
		}
		if !beforeReal || !inHome(dir) {
			continue
		}
		if dirWritable(dir) {
			return dir, true
		}
	}
	// 任何 home 内可写目录也接受（PATH 顺序稍差但可用）。
	for _, dir := range entries {
		if dir != "" && inHome(dir) && dirWritable(dir) {
			return dir, true
		}
	}
	return filepath.Join(home, ".local", "bin"), false
}

func dirWritable(dir string) bool {
	info, err := os.Stat(dir)
	return err == nil && info.IsDir()
}

// cmdShimInstall 安装 shim（显式 opt-in）。
func cmdShimInstall(args []string) error {
	fs := flag.NewFlagSet("shim install", flag.ContinueOnError)
	port := fs.Int("port", defaultPort(), "router port")
	if err := fs.Parse(args); err != nil {
		return err
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	realCodex := resolveRealCodex()
	if realCodex == "" {
		return fmt.Errorf("no real codex found on PATH; nothing to wrap")
	}
	targetDir, onPath := shimTargetDir(home, realCodex)
	target := filepath.Join(targetDir, shimCommand)

	// 红线：目标已有非 shim 的 codex → 拒绝（别人的刻意设置）。
	if _, err := os.Stat(target); err == nil && !isShimFile(target) {
		return fmt.Errorf("refusing to overwrite a codex wrapper that is not ours at %s", target)
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	checkout, err := os.Getwd()
	if err != nil {
		return err
	}
	script := renderShim(realCodex, checkout, *port)
	if err := os.WriteFile(target, []byte(script), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(target, 0o755); err != nil {
		return err
	}
	fmt.Printf("shim installed: %s\n  wraps: %s\n", target, realCodex)
	if !onPath {
		fmt.Printf("\n%s is not on your PATH. Add it with:\n  export PATH=%s:$PATH\n", targetDir, targetDir)
	}
	return nil
}

// cmdShimUninstall 删除 shim（只删带 marker 的）。
func cmdShimUninstall(args []string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	removed := false
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" {
			continue
		}
		candidate := filepath.Join(dir, shimCommand)
		if isShimFile(candidate) {
			if err := os.Remove(candidate); err != nil {
				return err
			}
			fmt.Printf("shim removed: %s\n", candidate)
			removed = true
		}
	}
	fallback := filepath.Join(home, ".local", "bin", shimCommand)
	if !removed && isShimFile(fallback) {
		if err := os.Remove(fallback); err != nil {
			return err
		}
		fmt.Printf("shim removed: %s\n", fallback)
		removed = true
	}
	if !removed {
		fmt.Println("no shim installed")
	}
	return nil
}

// cmdShimStatus 报告 shim 状态。
func cmdShimStatus(args []string) error {
	installed, file := "", ""
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" {
			continue
		}
		candidate := filepath.Join(dir, shimCommand)
		if isShimFile(candidate) {
			installed, file = "yes", candidate
			break
		}
	}
	if installed == "" {
		fmt.Printf("installed: no\nreal codex: %s\n", orDash(resolveRealCodex()))
		return nil
	}
	fmt.Printf("installed: yes\nshim: %s\nreal codex: %s\n", file, orDash(resolveRealCodex()))
	return nil
}

func orDash(value string) string {
	if value == "" {
		return "(not found)"
	}
	return value
}
